<script lang="ts" setup>
import { PublicKey } from '@solana/web3.js'
import { getParsedAccountByMint } from '@nfteyez/sol-rayz'
import { getAssociatedTokenAddress } from '@solana/spl-token'
import { Metaplex, JsonMetadata } from '@metaplex-foundation/js'

const anchorWallet = useAnchorWallet()
const $router = useRouter()
const { nftbox } = useContract()
const { connection } = useConnection()

const model = ref({
  name: 'My Misterious Box NFTs',
  description: 'This is a box set of NFTs',
  image: 'https://api.dicebear.com/5.x/pixel-art/svg?seed=Example&autogenerated',
  max_supply: 100,
  mint: '',
  master_edition: '',
  metadata: '',
  token_account: '',
})

const boxSetAddress = computed(() => nftbox.value?.findPDABoxSet(
  anchorWallet.value?.publicKey || new PublicKey(''),
  model.value.name
)?.toBase58() || '')

const loading = ref(false)
const error = ref<string>()
const submit = async () => {
  if (!anchorWallet.value) return

  error.value = undefined
  loading.value = true
  try {
    console.log('a')
    const created = await nftbox.value?.boxset()?.create(
      model.value.name,
      model.value.description,
      model.value.image,
      model.value.max_supply,
    )
    console.log('created', created)

    alert('Box Set Created')

    $router.push('/')
  } catch (err) {
    if (err instanceof Error) {
      error.value = `${err.message} (${err.name})`
    }
    console.error(err)
  }

  loading.value = false
}

const fetchVoucherNft = async () => {
  if (!anchorWallet.value?.publicKey) {
    alert(`please connect wallet`)
    return
  }

  const m = new PublicKey(model.value.mint)
  const _data = await connection.value?.getParsedAccountInfo(m)

  if ((_data?.value?.data as any)?.program !== "spl-token") {
    alert(`this mint nft is not from program spl-token`)
    return
  }

  if ((_data?.value?.data as any)?.parsed?.type !== "mint") {
    alert(`this mint nft is not type mint`)
    return
  }

  const decimals = (_data?.value?.data as any)?.parsed?.info?.decimals
  const supply = (_data?.value?.data as any)?.parsed?.info?.supply
  if (decimals !== 0 || supply !== "1") {
    alert(`this mint nft is not master edition | decimals ${decimals} | supply ${supply}`)
    return
  }
  const mintAuthority = (_data?.value?.data as any)?.parsed?.info?.mintAuthority || ''
  console.log('data', _data, mintAuthority)

  // get
  const nft = await getParsedAccountByMint({
    mintAddress: m.toString(),
    connection: connection.value,
  })
  const nftAuthority = nft?.account?.data?.parsed?.info?.owner

  if (nftAuthority !== anchorWallet.value?.publicKey?.toString()) {
    alert(`this owner mint nft is not you | owner : ${nftAuthority}`)
    return
  }

  // get master edition > edition metadata
  const metaplex_id = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
  const [pdaMasterEdition] = PublicKey.findProgramAddressSync(
    [
      Buffer.from("metadata"),
      new PublicKey(metaplex_id).toBuffer(),
      m.toBuffer(),
      Buffer.from("edition"),
    ],
    new PublicKey(metaplex_id)
  )
  model.value.master_edition = pdaMasterEdition.toString()


  const [pdaNftMetadata] = PublicKey.findProgramAddressSync(
    [
      Buffer.from("metadata"),
      new PublicKey(metaplex_id).toBuffer(),
      m.toBuffer(),
    ],
    new PublicKey(metaplex_id)
  )
  model.value.metadata = pdaNftMetadata.toString()

  const token = await getAssociatedTokenAddress(m, anchorWallet.value?.publicKey)
  model.value.token_account = token.toBase58()
}
</script>

<template>
  <Card>
    <template #header>
      <div class="font-bold text-xl">Create Box Set</div>
    </template>
    <div v-if="!anchorWallet" class="text-center">Connect Wallet to continue</div>
    <div v-else class="flex flex-col space-y-4">
      <div class="flex">
        <div class="w-1/5 mt-2">Authority Address</div>
        <div class="flex-1">
          <input type="text" class="w-full border-2 border-white/10 rounded-lg px-4 py-2 bg-transparent text-white read-only:bg-slate-800" readonly :value="anchorWallet?.publicKey?.toString()" />
        </div>
      </div>
      <div class="flex">
        <div class="w-1/5 mt-2">Box Set Address</div>
        <div class="flex-1">
          <input type="text" class="w-full border-2 border-white/10 rounded-lg px-4 py-2 bg-transparent text-white read-only:bg-slate-800" readonly :value="boxSetAddress" />
          <div class="font-thin text-sm mt-1">
            * this is generate automaticly (pda) from seed (authority + name)
          </div>
        </div>
      </div>
      <div class="flex">
        <div class="w-1/5 mt-2">Box Set Name</div>
        <div class="flex-1">
          <input type="text" class="w-full border-2 border-white/10 rounded-lg px-4 py-2 bg-transparent text-white read-only:bg-slate-800" v-model="model.name" />
        </div>
      </div>
      <div class="flex">
        <div class="w-1/5 mt-2">Box Set Description</div>
        <div class="flex-1">
          <input type="text" class="w-full border-2 border-white/10 rounded-lg px-4 py-2 bg-transparent text-white read-only:bg-slate-800" v-model="model.description" />
        </div>
      </div>
      <div class="flex">
        <div class="w-1/5 mt-2">Box Set Image</div>
        <div class="flex-1">
          <input type="text" class="w-full border-2 border-white/10 rounded-lg px-4 py-2 bg-transparent text-white read-only:bg-slate-800" v-model="model.image" />
        </div>
      </div>
      <div class="flex">
        <div class="w-1/5 mt-2">Box Set Max Supply</div>
        <div class="flex-1">
          <input type="number" class="w-full border-2 border-white/10 rounded-lg px-4 py-2 bg-transparent text-white read-only:bg-slate-800" v-model="model.max_supply" />
        </div>
      </div>
      <div class="border-b-2 w-full pt-4 pb-2 border-slate-700">
        <div class="text-3xl font-bold">Voucher</div>
      </div>
      <div class="flex">
        <div class="w-2/6 mt-2">Master Edition Mint Address</div>
        <div class="flex-1">
          <div class="flex space-x-4">
            <input type="text" class="w-full border-2 border-white/10 rounded-lg px-4 py-2 bg-transparent text-white read-only:bg-slate-800" v-model="model.mint" />
            <Button text="Fetch" @click="fetchVoucherNft" />
          </div>
          <div class="font-thin text-sm mt-1">
            * use mint from your nft master edition, we automatically fill the rest of the fields
          </div>
        </div>
      </div>
      <div class="flex">
        <div class="w-2/6 mt-2">Master Edition > Edition Metadata</div>
        <div class="flex-1">
          <input type="text" class="w-full border-2 border-white/10 rounded-lg px-4 py-2 bg-transparent text-white read-only:bg-slate-800" readonly v-model="model.master_edition" />
        </div>
      </div>
      <div class="flex">
        <div class="w-2/6 mt-2">Master Edition > Nft Metadata</div>
        <div class="flex-1">
          <input type="text" class="w-full border-2 border-white/10 rounded-lg px-4 py-2 bg-transparent text-white read-only:bg-slate-800" readonly v-model="model.metadata" />
        </div>
      </div>
      <div class="flex">
        <div class="w-2/6 mt-2">Token</div>
        <div class="flex-1">
          <input type="text" class="w-full border-2 border-white/10 rounded-lg px-4 py-2 bg-transparent text-white read-only:bg-slate-800" readonly v-model="model.token_account" />
        </div>
      </div>
      <div class="flex items-center justify-between">
        <div>
          <div v-if="error" class="text-red-500">* Error : {{ error }}</div>
        </div>
        <button v-if="anchorWallet" class="bg-primary-500 rounded-lg px-4 py-2 text-white font-bold" @click="submit">
          Create
        </button>
      </div>
    </div>
  </Card>
</template>
