<script lang="ts" setup>
import { PublicKey } from '@solana/web3.js'

const anchorWallet = useAnchorWallet()
const $router = useRouter()
const { nftbox } = useContract()

const model = ref({
  name: 'My Misterious Box NFTs',
  description: 'This is a box set of NFTs',
  image: 'https://api.dicebear.com/5.x/pixel-art/svg?seed=Example&autogenerated',
  max_supply: 100,
})

const boxSetAddress = computed(() => nftbox.value?.findPDABoxSet(
  anchorWallet.value?.publicKey || new PublicKey(''),
  model.value.name
)?.toBase58() || '')

const loading = ref(false)
const error = ref<string>()
const submit = async () => {
  if (!anchorWallet.value) return

  error.value = undefined
  loading.value = true
  try {
    console.log('a')
    const created = await nftbox.value?.boxset()?.create(
      model.value.name,
      model.value.description,
      model.value.image,
      model.value.max_supply,
    )
    console.log('created', created)

    alert('Box Set Created')

    $router.push('/')
  } catch (err) {
    if (err instanceof Error) {
      error.value = `${err.message} (${err.name})`
    }
  }

  loading.value = false
}
</script>

<template>
  <Card>
    <template #header>
      <div class="font-bold text-xl">Create Box Set</div>
    </template>
    <div v-if="!anchorWallet" class="text-center">Connect Wallet to continue</div>
    <div v-else class="flex flex-col space-y-4">
      <div class="flex">
        <div class="w-1/5 mt-2">Authority Address</div>
        <div class="flex-1">
          <input type="text" class="w-full border-2 border-white/10 rounded-lg px-4 py-2 bg-transparent text-white read-only:bg-slate-800" readonly :value="anchorWallet?.publicKey?.toString()" />
        </div>
      </div>
      <div class="flex">
        <div class="w-1/5 mt-2">Box Set Address</div>
        <div class="flex-1">
          <input type="text" class="w-full border-2 border-white/10 rounded-lg px-4 py-2 bg-transparent text-white read-only:bg-slate-800" readonly :value="boxSetAddress" />
          <div class="font-thin text-sm mt-1">
            * this is generate automaticly (pda) from seed (authority + name)
          </div>
        </div>
      </div>
      <div class="flex">
        <div class="w-1/5 mt-2">Box Set Name</div>
        <div class="flex-1">
          <input type="text" class="w-full border-2 border-white/10 rounded-lg px-4 py-2 bg-transparent text-white read-only:bg-slate-800" v-model="model.name" />
        </div>
      </div>
      <div class="flex">
        <div class="w-1/5 mt-2">Box Set Description</div>
        <div class="flex-1">
          <input type="text" class="w-full border-2 border-white/10 rounded-lg px-4 py-2 bg-transparent text-white read-only:bg-slate-800" v-model="model.description" />
        </div>
      </div>
      <div class="flex">
        <div class="w-1/5 mt-2">Box Set Image</div>
        <div class="flex-1">
          <input type="text" class="w-full border-2 border-white/10 rounded-lg px-4 py-2 bg-transparent text-white read-only:bg-slate-800" v-model="model.image" />
        </div>
      </div>
      <div class="flex">
        <div class="w-1/5 mt-2">Box Set Max Supply</div>
        <div class="flex-1">
          <input type="number" class="w-full border-2 border-white/10 rounded-lg px-4 py-2 bg-transparent text-white read-only:bg-slate-800" v-model="model.max_supply" />
        </div>
      </div>
      <div class="flex items-center justify-between">
        <div>
          <div v-if="error" class="text-red-500">* Error : {{ error }}</div>
        </div>
        <button v-if="anchorWallet" class="bg-primary-500 rounded-lg px-4 py-2 text-white font-bold" @click="submit">
          Create
        </button>
      </div>
    </div>
  </Card>
</template>
