[package]
name = "nftbox"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "nftbox"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.27.0"
anchor-spl = { version="0.27.0", features = [ "metadata" ] }
spl-token = "3.5.0"
solana-program = "1.15.2"
mpl-token-metadata = { version="1.9.1", features = [ "no-entrypoint" ] }
