[features]
seeds = false
skip-lint = false

[programs.devnet]
nftbox = "D4YkZGgDuoWUeasNPY6prAWXk129YUL9xXXhw7K2wPCR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/viandwi24/.config/solana/id.json"

[scripts]
test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
