[features]
seeds = false
skip-lint = false

[programs.devnet]
nftbox = "2R4MEs4jN1vU22HSThywX5hy3RW5VPPavUseVgGFQ3Kc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/viandwi24/.config/solana/id.json"

[scripts]
test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
